# Site settings
title: Web scraping with Nokogiri: Function or Folly?
header-img: img/home-bg.png
email: jokerdelta@yahoo.com
copyright_name: jokerdelta
description: > # this means to ignore newlines until "baseurl:"
  A fledgling Ruby dev's foray into the volatile world of web scraping.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jokerdelta
github_username:  jokerdelta
learn_profile: jokerdelta
email_username: jokerdelta@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
